apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: quantum-prometheus
  namespace: monitoring
  labels:
    app: prometheus
    component: monitoring
spec:
  replicas: 2
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      release: prometheus
  podMonitorSelector:
    matchLabels:
      release: prometheus
  resources:
    requests:
      memory: 4Gi
      cpu: "1"
    limits:
      memory: 8Gi
      cpu: "2"
  retention: 15d
  retentionSize: "50GB"
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: quantum
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager
      port: web
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: quantum-prometheus
  namespace: monitoring
  labels:
    app: prometheus
    component: monitoring
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    prometheus: quantum-prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quantum-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: quantum-app
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
  namespaceSelector:
    matchNames:
    - quantum-prod
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: quantum-pod-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: quantum-app
  podMetricsEndpoints:
  - port: http
    interval: 15s
    path: /metrics
  namespaceSelector:
    matchNames:
    - quantum-prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-additional-scrape
  namespace: monitoring
data:
  prometheus-additional.yaml: |
    - job_name: 'quantum-redis'
      static_configs:
      - targets: ['quantum-redis:9121']
    - job_name: 'quantum-postgres'
      static_configs:
      - targets: ['quantum-postgres:9187']